# Web-Scraping-Assignment with BeautifulSoup, Selenium and Exception Handling

In [1]:
# Importing the necessary libraries
import pandas as pd
import time
import selenium
from bs4 import BeautifulSoup

#Importing warnings
import warnings
warnings.simplefilter("ignore")
warnings.filterwarnings("ignore")

# Importing selenium webdriver 
from selenium import webdriver

# Importing the required Exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException,ElementNotInteractableException

#Importing requests
import requests

# importing regex
import re

1. Scrape the details of most viewed videos on YouTube from Wikipedia: Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/ 

You need to find following details:

A) Rank 

B) Name 

C) Artist 

D) Upload date 

E) Views

In [5]:
 #path for chromedriver
driver = webdriver.Chrome(executable_path='chromedriver.exe')

# to open the webpage
url = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)
driver.maximize_window()

time.sleep(2)

In [7]:
#empty lists to store the data
name= []
rank= []
artist=[]
upld_dt=[]
views=[]

#scraping the rank
try:
    rnk=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]")
    for i in rnk:
        rank.append(i.text)
except NoSuchElementException:
    rank.append('No details')
    
time.sleep(1)
#scraping the video names
try:
    names=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:
    name.append('No details')

time.sleep(1)

#scraping the artist name
try:
    art=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in art:
        artist.append(i.text)
except NoSuchElementException:
    artist.append('No details')
    
time.sleep(1)

#scraping the views
try:
    view=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in view:
        views.append(i.text)
except NoSuchElementException:
    views.append('No details')   

time.sleep(1)
#scraping the video upload_date
try:
    date=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in date:
        upld_dt.append(i.text)
except NoSuchElementException:
    upld_dt.append('No details')
    
#Making dataframe
df=pd.DataFrame({"Rank":rank,
                 "Name":name,
                "Artist":artist,
                "Upload date":upld_dt,
                "Views(billions)":views})
df

,Rank,Name,Artist,Upload date,Views(billions)
0,1.,"""Baby Shark Dance""[23]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",9.44
1,2.,"""Despacito""[25]",Luis Fonsi,"January 12, 2017",7.57
2,3.,"""Johny Johny Yes Papa""[26]",LooLoo Kids,"October 8, 2016",5.77
3,4.,"""Shape of You""[27]",Ed Sheeran,"January 30, 2017",5.48
4,5.,"""See You Again""[28]",Wiz Khalifa,"April 6, 2015",5.28
5,6.,"""Bath Song""[31]",Cocomelon – Nursery Rhymes,"May 2, 2018",4.55
6,7.,"""Learning Colors – Colorful Eggs on a Farm""[32]",Miroshka TV,"February 27, 2018",4.52
7,8.,"""Masha and the Bear – Recipe for Disaster""[33]",Get Movies,"January 31, 2012",4.46
8,9.,"""Uptown Funk""[34]",Mark Ronson,"November 19, 2014",4.32
9,10.,"""Phonics Song with Two Words""[35]",ChuChu TV,"March 6, 2014",4.22
10,11.,"""Gangnam Style""[36]",Psy,"July 15, 2012",4.21
11,12.,"""Dame Tu Cosita""[38]",El Chombo,"April 5, 2018",3.63
12,13.,"""Sugar""[39]",Maroon 5,"January 14, 2015",3.56
13,14.,"""Sorry""[40]",Justin Bieber,"October 22, 2015",3.47
14,15.,"""Roar""[41]",Katy Perry,"September 5, 2013",3.44
15,16.,"""Counting Stars""[42]",OneRepublic,"May 31, 2013",3.41
16,17.,"""Thinking Out Loud""[43]",Ed Sheeran,"October 7, 2014",3.34
17,18.,"""Wheels on the Bus""[44]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.29
18,19.,"""Dark Horse""[45]",Katy Perry,"February 20, 2014",3.15
19,20.,"""Faded""[46]",Alan Walker,"December 3, 2015",3.15
20,21.,"""Girls Like You""[47]",Maroon 5,"May 31, 2018",3.14
21,22.,"""Lean On""[48]",Major Lazer,"March 22, 2015",3.10
22,23.,"""Bailando""[49]",Enrique Iglesias,"April 11, 2014",3.10
23,24.,"""Shake It Off""[50]",Taylor Swift,"August 18, 2014",3.10
24,25.,"""Let Her Go""[51]",Passenger,"July 25, 2012",3.09
25,26.,"""Axel F""[52]",Crazy Frog,"June 16, 2009",3.03
26,27.,"""Mi Gente""[53]",J Balvin,"June 29, 2017",2.99
27,28.,"""Perfect""[54]",Ed Sheeran,"November 9, 2017",2.97
28,29.,"""Waka Waka (This Time for Africa)""[55]",Shakira,"June 4, 2010",2.96
29,30.,"""Hello""[56]",Adele,"October 22, 2015",2.89

2. Scrape the details team India’s international fixtures from bcci.tv.

Url = https://www.bcci.tv/.

You need to find following details:

A) Match title (I.e. 1st ODI)

B) Series

C) Place

D) Date

E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [91]:
#path for chromedriver
driver = webdriver.Chrome(executable_path='chromedriver.exe')

# to open the webpage
url = 'https://www.bcci.tv/'
driver.get(url)
driver.maximize_window()

time.sleep(2)

In [90]:
#to see content of page
soup = BeautifulSoup(page.content)

#clicking the fixtures icon
button=driver.find_element_by_xpath("//div[@class = 'navigation__drop-down drop-down drop-down--reveal-on-hover']/div/ul/li/a")
driver.get(button.get_attribute("href"))
time.sleep(2)

#empty lists to store the data
match_title=[]
series=[]
place=[]
date=[]
dt_time=[]
mtch_time=[]

#scraping the title of the match
for i in driver.find_elements_by_xpath("//div[@class='fixture__format-strip']/span[@class='u-unskewed-text fixture__format']"):
    try:
        match_title.append(i.text)
    except NoSuchElementException:
        match_title.append('--')

time.sleep(1)
#scraping the series name
for i in driver.find_elements_by_xpath("//div[@class='fixture__format-strip']/span[@class='u-unskewed-text fixture__tournament-label u-truncated']"):
    try:
        series.append(i.text)
    except NoSuchElementException:
        series.append('--')

time.sleep(1)
#scraping the venue
for i in driver.find_elements_by_xpath("//div[@class='fixture__description u-unskewed-text']/p/span"):
    try:
        place.append(i.text)
    except NoSuchElementException:
        place.append('--')

time.sleep(1)
#scraping the date-time
for i in driver.find_elements_by_xpath("//div[@class='fixture__datetime desktop-only']"):
    try:
        dt_time.append(i.text.replace('\n',' '))
    except NoSuchElementException:
        dt_time.append('--')

#splitting the date and time
date=[i.split(' ',3)[:3] for i in dt_time]
date=[' '.join(i) for i in date]
mtch_time=[i.split(' ',3)[-1] for i in dt_time]

# Creating data frame
df=pd.DataFrame({'Match Title': match_title,
                          "Series": series,
                          "Place": place,
                          "Date": date,
                          "Time": mtch_time})
df

,Match Title,Series,Place,Date,Time
0,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",Sunday 24 OCTOBER,19:30 IST
1,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",Sunday 31 OCTOBER,19:30 IST
2,T20I,2021 ICC MEN'S T20 WORLD CUP,"Zayed Cricket Stadium, Abu Dhabi",Wednesday 03 NOVEMBER,19:30 IST
3,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",Friday 05 NOVEMBER,19:30 IST
4,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",Monday 08 NOVEMBER,19:30 IST
5,T20I,INDIA V NEW ZEALAND 2021,"Sawai Mansingh Stadium, Jaipur",Wednesday 17 NOVEMBER,19:00 IST
6,T20I,INDIA V NEW ZEALAND 2021,"JSCA International Stadium Complex, Ranchi",Friday 19 NOVEMBER,19:00 IST
7,T20I,INDIA V NEW ZEALAND 2021,"Eden Gardens, Kolkata",Sunday 21 NOVEMBER,19:00 IST
8,TEST,INDIA V NEW ZEALAND 2021,"Green Park, Kanpur",Thursday 25 NOVEMBER,09:30 IST
9,TEST,INDIA V NEW ZEALAND 2021,"Wankhede Stadium, Mumbai",Friday 03 DECEMBER,09:30 IST
10,TEST,SOUTH AFRICA V INDIA 2021/2022,"New Wanderers Stadium, Johannesburg",Friday 17 DECEMBER,13:30 IST
11,TEST,SOUTH AFRICA V INDIA 2021/2022,"Supersport Park, Centurion",Sunday 26 DECEMBER,13:30 IST
12,TEST,SOUTH AFRICA V INDIA 2021/2022,"New Wanderers Stadium, Johannesburg",Monday 03 JANUARY,13:30 IST
13,ODI,SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",Tuesday 11 JANUARY,14:00 IST
14,ODI,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",Friday 14 JANUARY,14:00 IST
15,ODI,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",Sunday 16 JANUARY,14:00 IST
16,T20I,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",Wednesday 19 JANUARY,19:30 IST
17,T20I,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",Friday 21 JANUARY,19:30 IST
18,T20I,SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",Sunday 23 JANUARY,19:30 IST
19,T20I,SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",Wednesday 26 JANUARY,19:30 IST

3. Scrape the details of selenium exception from guru99.com. 

Url = https://www.guru99.com/

You need to find following details:

A) Name

B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [94]:
#path for chromedriver
driver = webdriver.Chrome(executable_path='chromedriver.exe')

# to open the webpage
url = 'https://www.guru99.com/'
driver.get(url)
driver.maximize_window()

time.sleep(2)
#to see the page content
soup = BeautifulSoup(page.content)

In [95]:
#clicking on the selenium icon
sel= driver.find_element_by_xpath('//*[@id="java_technologies"]/li[3]/a')
try:
    sel.click()
except ElementNotInteractableException:
    driver.get(sel.get_attribute('href'))

time.sleep(3)
#clicking on Selenium Exception Handling (Common Exceptions List)
exception= driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a').get_attribute('href')
driver.get(exception)

time.sleep(2)
#empty lists to store data
name=[]
description=[]

#scraping exceptions name
try:
    names=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]")
    for i in names[1:]:
        name.append(i.text)
except NoSuchElementException:         
    name.append('--')

time.sleep(1)   
#scraping exceptions description
try:
    desc=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]")
    for i in desc[1:]:
        description.append(i.text)
except NoSuchElementException:
    description.append('--')

time.sleep(1)
#making a dataframe
df=pd.DataFrame({"Exception name": name, 
                 "Exception description": description})
df

,Exception name,Exception description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

4. Scrape the details of State-wise GDP of India from statisticstime.com. 

Url = http://statisticstimes.com/

You have to find following details:

A) Rank

B) State

C) GSDP at current price (19-20)

D) GSDP at current price (18-19)

E) Share(18-19)

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [9]:
#path for chromedriver
driver = webdriver.Chrome(executable_path='chromedriver.exe')

# to open the webpage
url = 'http://statisticstimes.com/'
driver.get(url)
driver.maximize_window()

time.sleep(2)

In [10]:
#clicking on economy button
eco=driver.find_element_by_xpath("//div[@class='dropdown'][2]/div/a[3]")
try:
    eco.click()
except ElementNotInteractableException:
    driver.get(eco.get_attribute('href'))
time.sleep(2)

In [11]:
#clicking on GDP of Indian states
Ind_states=driver.find_element_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']//li[1]/a")

try:
    Ind_states.click()
except ElementNotInteractableException:
    driver.get(Ind_states.get_attribute('href')) 
time.sleep(2)

#empty lists to store the data
Rank = []
State = []
GSDP20 = []
GSDP19  = []
Share = []
GDP_Billion = []

#scraping the rank
try:
    rank=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[1]")
    for i in rank:
        Rank.append(i.text)
except NoSuchElementException:                
    Rank.append('--')

time.sleep(1)
#scraping the States
try:
    states=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[2]")
    for i in states:
        State.append(i.text)
except NoSuchElementException:
    State.append('--')

time.sleep(1)
#scraping GSDP(19-20)
try:
    gsdp1=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[3]")
    for i in gsdp1:
        GSDP20.append(i.text)
except NoSuchElementException:    
    GSDP20.append('--')

time.sleep(1)    
#scraping GSDP(18-19)
try:
    gsdp2=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[4]")
    for i in gsdp2:
        GSDP19.append(i.text)
except NoSuchElementException:
    GSDP19.append('--')

time.sleep(1)
#scraping the share (18-19)
try:
    sh=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[5]")
    for i in sh:
        Share.append(i.text)
except NoSuchElementException:      
    Share.append('--')

time.sleep(1)
#scraping GDP(in billion)
try:
    gdp=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[6]")
    for i in gdp:
        GDP_Billion.append(i.text)
except NoSuchElementException:           
    GDP_Billion.append('--')
time.sleep(1)

#Making dataframe
df=pd.DataFrame({'Rank':Rank,
                'State':State,
                'GSDP(19-20)':GSDP20,
                'GSDP(18-19)':GSDP19,
                'Share(18-19)':Share,
                'GDP($Billion)':GDP_Billion})
df

,Rank,State,GSDP(19-20),GSDP(18-19),Share(18-19),GDP($Billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

5. Scrape the details of trending repositories on Github.com.

Url = https://github.com/

You have to find the following details:

A) Repository title

B) Repository description

C) Contributors count

D) Language used

In [27]:
#path for chromedriver
driver = webdriver.Chrome(executable_path='chromedriver.exe')

# to open the webpage
url = 'https://github.com/'
driver.get(url)
driver.maximize_window()

time.sleep(2)

In [28]:
# clicking the explore button
exp=driver.find_element_by_xpath("//details[@class='HeaderMenu-details details-overlay details-reset width-full']/summary")
try:
    exp.click()
except:
    driver.get(exp.get_attribute('href'))
time.sleep(1)

#finding the trending option
trend=driver.find_element_by_xpath("//ul[@class='list-style-none mb-3']/li[3]/a")
try:
    trend.click()
except:
    driver.get(trend.get_attribute('href'))
time.sleep(1)


#empty lists to store the data   
urls=[]
title=[]
desc=[]
contributor=[]
language=[]


#scraping urls of repositories
repo_url=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")
for i in repo_url:
    urls.append(i.get_attribute('href'))

time.sleep(1) 
#scraping title of repositories 
try:
    repo=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']")
    for i in repo:
        title.append(i.text)
except NoSuchElementException:
    title.append('--')

time.sleep(1)

for i in urls:
    driver.get(i)
    time.sleep(1)
    
    #scraping description of repositories
    try:
        repo_desc = driver.find_element_by_xpath("/html/body/div[4]/div/main/div[2]/div/div/div[2]/div[2]/div/div[1]/div/p")
        desc.append(repo_desc.text)
    except NoSuchElementException:
        desc.append('--')
    
    #scraping the contributors_count
    try:
        count=driver.find_element_by_xpath("//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        contributor.append(count.text)
    except NoSuchElementException:
        contributor.append('--')
    time.sleep(2)
    
     #scraping used languages
    lang=[]
    languages=driver.find_elements_by_xpath("//li[@class='d-inline']//a//span[1]")
    if languages:    
        for i in languages:
            lang.append(i.text)
    else:
        lang.append('--')
    language.append(lang)
    
time.sleep(1)   
#Making dataframe
df=pd.DataFrame({'Repository Title':title,
                'Repository Description':desc,
                'Contributors Count':contributor,
                'Language Used':language})
df

,Repository Title,Repository Description,Contributors Count,Language Used
0,peng-zhihui / Dummy-Robot,我的超迷你机械臂机器人项目。,--,[--]
1,trailofbits / algo,Set up a personal VPN in the cloud,156,"[Python, Jinja, Shell]"
2,Snailclimb / JavaGuide,「Java学习+面试指南」一份涵盖大部分 Java 程序员所需要掌握的核心知识。准备 Jav...,261,[Java]
3,louislam / uptime-kuma,A fancy self-hosted monitoring tool,60,"[JavaScript, Vue, SCSS, Shell, TypeScript, Doc..."
4,vuejs / vue-next,"Vue.js is a progressive, incrementally-adoptab...",280,"[TypeScript, HTML, JavaScript]"
5,babysor / MockingBird,AI拟声: 5秒内克隆您的声音并生成任意语音内容 Clone a voice in 5 se...,10,"[JavaScript, Python, HTML]"
6,facebook / flipper,A desktop debugging platform for mobile develo...,219,"[TypeScript, Java, Ruby, Objective-C++, C++, O..."
7,fatedier / frp,A fast reverse proxy to help you expose a loca...,71,"[Go, Vue, JavaScript, Shell, HTML, Makefile, L..."
8,ossrs / srs,"SRS is a simple, high efficiency and realtime ...",64,"[C++, JavaScript, ActionScript, HTML, Shell, P..."
9,vinta / awesome-python,"A curated list of awesome Python frameworks, l...",392,"[Python, Makefile]"
10,yt-dlp / yt-dlp,A youtube-dl fork with additional features and...,854,[Python]
11,ihciah / clean-dns-bpf,基于 Rust + eBPF 丢弃 GFW DNS 污染包,--,[Rust]
12,sdras / awesome-actions,A curated list of awesome actions to use on Gi...,280,[--]
13,Hack-with-Github / Awesome-Hacking,A collection of various awesome lists for hack...,21,[--]
14,anncwb / vue-vben-admin,"A modern vue admin. It is based on Vue3, vite ...",72,"[Vue, TypeScript, Less, JavaScript, CSS, HTML]"
15,Python-World / Python_and_the_Web,"Build Bots, Scrape a website or use an API to ...",102,"[Python, TeX, HTML]"
16,wimpysworld / quickemu,"Quickly create and run optimised Windows, macO...",16,"[Shell, Python]"
17,mattiasgustavsson / dos-like,"Engine for making things with a MS-DOS feel, b...",3,[C]
18,apache / rocketmq,Mirror of Apache RocketMQ,280,[Java]
19,donet5 / WebFirst,.NET CORE 代码生成器 ，Web中使用CodeFirst模式， 实体生成器，UI代码...,--,"[C#, CSS, HTML]"
20,raywenderlich / flta-materials,The projects and the materials that accompany ...,8,"[Dart, Ruby, Swift, HTML, Kotlin, Shell, Objec..."
21,herosi / CTO,Call Tree Overviewer,--,[Python]
22,alibaba / Sentinel,A powerful flow control component enabling rel...,152,"[Java, JavaScript, HTML, CSS, Shell, Dockerfile]"
23,alibaba / spring-cloud-alibaba,Spring Cloud Alibaba provides a one-stop solut...,114,[Java]
24,vuejs / vue,"Vue.js is a progressive, incrementally-adoptab...",401,[JavaScript]

6. Scrape the details of top 100 songs on billboard.com.

Url = https://www.billboard.com/

You have to find the following details:

A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [29]:
#path for chromedriver
driver = webdriver.Chrome(executable_path='chromedriver.exe')

# to open the webpage
url = 'https://www.billboard.com/'
driver.get(url)
driver.maximize_window()

time.sleep(2)

In [30]:
#clicking on Hot 100 
hot100=driver.find_element_by_xpath("//ul[@class='header__subnav__list display--flex flex--left-center flex-md--center-center']//li[3]//a")
try:
    hot100.click()
except ElementNotInteractableException:
    driver.get(hot100.get_attribute('href'))
time.sleep(2)

In [32]:
#empty lists to store the data
Song_name=[]
Artist_name=[]
Last_week_Rank=[]
Peak_rank=[]
Weeks_on_board=[]

#scraping name of the song
try:
    name=driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']")
    for i in name:
        Song_name.append(i.text)
except NoSuchElementException: 
    Song_name.append('--')

time.sleep(1)    
#scraping name of the artist 
try:
    art=driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']")
    for i in art:
        Artist_name.append(i.text)
except NoSuchElementException:    
    Artist_name.append('--')

time.sleep(1)
#scraping last week rank
try:
    rank=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")
    for i in rank:
        Last_week_Rank.append(i.text)
except NoSuchElementException:   
    Last_week_Rank.append('--') 

time.sleep(1)
#scraping the peak rank the song reached
try:
    peak=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")
    for i in peak:
        Peak_rank.append(i.text)
except NoSuchElementException:  
    Peak_rank.append('--')

time.sleep(1)
#scraping the number of weeks on charts
try:
    week=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")
    for i in week:
        Weeks_on_board.append(i.text)
except NoSuchElementException:      
    Weeks_on_board.append('--')

time.sleep(1)
#making the dataframe
df=pd.DataFrame({'Song Name':Song_name,
                'Artist':Artist_name,
                'Last Week Rank':Last_week_Rank,
                'Peak':Peak_rank,
                'Weeks on Board':Weeks_on_board})
df

,Song Name,Artist,Last Week Rank,Peak,Weeks on Board
0,My Universe,Coldplay x BTS,-,1,1
1,Stay,The Kid LAROI & Justin Bieber,1,1,12
2,Industry Baby,Lil Nas X & Jack Harlow,2,2,10
3,Way 2 Sexy,Drake Featuring Future & Young Thug,3,1,4
4,Fancy Like,Walker Hayes,5,5,15
...,...,...,...,...,...
95,Pipe Down,Drake,68,14,4
96,Papi's Home,Drake,66,8,4
97,Chosen,Blxst & Tyga Featuring Ty Dolla $ign,-,98,1
98,Toxic Punk,YoungBoy Never Broke Again,-,99,1
99,Moon,Kanye West,76,17,5

7. Scrape the details of Data science recruiters from naukri.com.

Url = https://www.naukri.com/

You have to find the following details:

A) Name

B) Designation

C) Company

D) Skills they hire for

E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [74]:
# path for chromedriver
driver=webdriver.Chrome(executable_path="chromedriver.exe") 

# Opening the webpage
url = "https://www.naukri.com/"
driver.get(url)
driver.maximize_window()
time.sleep(2)

In [75]:
#clicking on recruiters option
recruit=driver.find_element_by_xpath("//a[@title='Search Recruiters']")
driver.get(recruit.get_attribute('href'))
time.sleep(1)

#accesing search bar
search=driver.find_element_by_xpath("//input[@class='sugInp']")
search.send_keys("Data Science")
time.sleep(1)

#clicking on search button
srch_btn=driver.find_element_by_xpath("//button[@id='qsbFormBtn']")
srch_btn.click()
time.sleep(1)

In [79]:
#empty lists to store the data
name = []
designation = []
company = []
skills = []
location = []

#scraping names
try:
    names=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[1]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:       
    name.append('--')

time.sleep(1)
#scraping designation
try:
    desig=driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
    for i in desig:
        designation.append(i.text)
except NoSuchElementException:     
    designation.append('--')

time.sleep(1)
#scraping names of company
try:
    comp=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[2]")
    for i in comp:
        company.append(i.text)
except NoSuchElementException:
    company.append('--')

time.sleep(1)
#scraping skills required
try:
    skill=driver.find_elements_by_xpath("//div[@class='recInfo']/div[2]")
    for i in skill:
        skills.append(i.text)
except NoSuchElementException:  
    skills.append('--')

time.sleep(1)  
#scraping location
soup=BeautifulSoup(driver.page_source,'html.parser')
loc=soup.find_all('div',attrs={'vcard'})
for i in loc:
    try:
        location.append(i.text)
    except NoSuchElementException:
        location.append("--")
time.sleep(1)
        
#creating dataframe
df=pd.DataFrame({'Name':name,
                'Designation':designation,
                'Company':company,
                "Location":location,
                'Skills/Roles I hire for':skills})
df

,Name,Designation,Company,Location,Skills/Roles I hire for
0,Aakash Harit,HR Manager,Data Science Network,Aakash Harit HR Manager Data Science Netw...,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,shravan Kumar Gaddam Company Recruiter Sh...,".Net, Java, Data Science, Linux Administration..."
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,MARSIAN Technologies LLP Company HR MARSI...,"Data Science, Artificial Intelligence, Machine..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Anik Agrawal Company Recruiter Enerlytics...,"Mean Stack, javascript, angularjs, mongodb, We..."
4,Narasimha,Company Recruiter,Step Next Private Limited,Narasimha Company Recruiter Step Next Pri...,"Data Modeling, Data Wrangling, seaborn, eda, p..."
5,subhas patel,Founder CEO,LibraryXProject,subhas patel Founder CEO LibraryXProject ...,"Hadoop, Spark, Digital Strategy, Data Architec..."
6,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Abhishek - Only Analytics Hiring - India ...,"Analytics, Business Intelligence, Business Ana..."
7,Institute for Financial Management and Resear,Programme Manager,IFMR,Institute for Financial Management and Re...,Data Science
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Balu Ramesh HR Administrator Techvantage ...,"Machine Learning, algorithms, Go Getter, Compu..."
9,Asif Lucknowi,Director,Weupskill- Live Wire India,Asif Lucknowi Director Weupskill- Live Wi...,"Technical Training, Software Development, Pres..."
10,InstaFinancials,Human Resource,CBL Data Science Private Limited,InstaFinancials Human Resource CBL Data S...,"Software Development, It Sales, Account Manage..."
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions Pvt.Ltd.,Priyanka Akiri HR Manager Infinitive Soft...,"Oracle Dba, Data Science, Data Warehousing, ET..."
12,Kalpana Dumpala,Executive Hiring,Innominds Software,Kalpana Dumpala Executive Hiring Innomind...,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
13,Mubarak,Company HR,MoneyTap,Mubarak Company HR MoneyTap Bengaluru / B...,"Business Intelligence, Data Warehousing, Data ..."
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,Kushal Rastogi Company HR QuantMagnum Tec...,"Office Administration, Hr Administration, tele..."
15,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Ruchi Dhote Senior Executive Talent Acqui...,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
16,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Mahesh Babu Channa HR Team Lead SocialPra...,"Social Media, digital media maketing, seo, smm..."
17,Kapil Devang,HR Manager,BISP Solutions,Kapil Devang HR Manager BISP Solutions Bh...,"Big Data, Hadoop, Data Analytics, Data Science"
18,Manisha Yadav,HR Executive,Easi Tax,Manisha Yadav HR Executive Easi Tax Navi ...,"Telecalling, Client Interaction, Marketing, Re..."
19,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Riya Rajesh Manager Talent Acquisition No...,Data Science
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Rashmi Bhattacharjee HR Head AXESTRACK SO...,"Corporate Sales, Software Development, Softwar..."
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Faizan Kareem HR MANAGER FirstTech Consal...,"Data Analytics, Data Science, Machine Learning..."
22,Rithika dadwal,HR Recruiter,Affine Analytics,Rithika dadwal HR Recruiter Affine Analyt...,"Data Science, Machine Learning, Python, R, Dee..."
23,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Sandhya Khandagale HR Recruiter Compumatr...,"Big Data, Data Science, Artificial Intelligenc..."
24,Shaun Rao,Manager Human Resources,Exela Technologies,Shaun Rao Manager Human Resources Exela T...,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Azahar Shaikh Company Recruiter NEAL ANAL...,"Data Science, Artificial Intelligence, Machine..."
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Manas Lead Talent acquisition Autumn Leaf...,"Software Architecture, Vp Engineering, Product..."
27,kumar,Proprietor,trainin,kumar Proprietor trainin Bengaluru / Bang...,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,Sunil Vedula CEO Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne..."
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Rajat Kumar Founder CEO R.S Consultancy &...,"Web Technologies, Project Management, Software..."
30,Priya Khare,Senior Manager,Independent Consultant,Priya Khare Senior Manager Independent Co...,"Data Science, Artificial Intelligence, analyti..."
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Dhruv Dev Dubey Company Recruitment Head ...,"Server Administartion, Verilog, Vhdl, Digital ..."
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Jayanth N Project Manager Dollarbird Info...,"Data Analytics, Managed Services, Team Leading..."
33,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,SREEDHAR Recruitment Consultant JOBSMILL ...,"Data Science, Machine Learning, Big Data Analy..."
34,Ravi Dubey,Recruitment Manager,HyrEzy Talent Solutions LLP,Ravi Dubey Recruitment Manager HyrEzy Tal...,Walmart Interra Skeps Expressstores indifi whi...
35,Radha Manivasagam,HR Executive,Techcovery,Radha Manivasagam HR Executive Techcovery...,"Python, Artificial Intelligence, Machine Learn..."
36,Prateek Kumar,Head,Trisect,Prateek Kumar Head Trisect Noida,"Java, Python, Angularjs, Software Testing, Mac..."
37,Amit Sharma,Consultant,ASCO consulting,Amit Sharma Consultant ASCO consulting Ne...,"Machine Learning, Artificial Intelligence, Dat..."
38,Kanan,senior technology instructor,NY INST,Kanan senior technology instructor NY INS...,"C, C++, Artificial Intelligence, Python, Php, ..."
39,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Shashikant Chaudhary HR Recruiter/HR Excu...,"Relationship Management, Retail Sales, Private..."
40,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Brad Manager, Technical Recruiting O.C. T...","Data Science, Software Engineering"
41,Rutuja Pawar,Technical Recruiter,Demand Matrix,Rutuja Pawar Technical Recruiter Demand M...,"Data Science, Big Data Analytics, Digital Mark..."
42,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Madhusudhan Sridhar Erp Implementer MADHU...,"Data Science, Recruitment, Salary"
43,Ankit Sinha,Head Analytics,Suntech Global,Ankit Sinha Head Analytics Suntech Global...,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
44,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Gaurav Chouhan Chief Technical Officer St...,"Software Development, Business Intelligence, B..."
45,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Rashi Kacker Sr Product Manager Impel Lab...,"Data Science, Node.js, Angularjs"
46,Ashwini,Director Global Delivery,MRP Advisers,Ashwini Director Global Delivery MRP Advi...,"Data Science, Media Marketing, Resource Planni..."
47,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Balaji Kolli Co Founder Saras Solutions I...,"Data Analysis, Learning, Data Science, Compute..."
48,Rajani Nagaraj,HR Manager,WildJasmine,Rajani Nagaraj HR Manager WildJasmine Ben...,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
49,ROHIT Kumar,Architect,LNT Private Limited,ROHIT Kumar Architect LNT Private Limited...,"Software Development, Core Java, Unit Testing,..."

8. Scrape the details of Highest selling novels.

Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/

You have to find the following details:

A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

In [48]:
#send get request to the webpage server to get the source code of the page
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/"
page = requests.get(url)
# to see content of the page
soup = BeautifulSoup(page.content)

#path for chromedriver
driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

#empty lists to store the data
book_name = []
author_name = []
volume_sold = []
publisher = []
genre = []

# Scraping Book name
try:
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[2]"):
        book_name.append(i.text)
except NoSuchElementException:
    book_name.append("-")

time.sleep(1)
# Scraping Author name    
try:
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[3]"):
        author_name.append(i.text)
except NoSuchElementException:
    author_name.append("--")

time.sleep(1)
# Scraping Volume sold
try: 
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[4]"):
        volume_sold.append(i.text)
except NoSuchElementException:
    volume_sold.append("--")

time.sleep(1)
#Scraping Genre
try: 
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[6]"):
        genre.append(i.text)
except NoSuchElementException:
    genre.append("--")
    
time.sleep(1)
# Scraping the Publishers
try:
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[5]"):
        publisher.append(i.text)
except NoSuchElementException:
    publisher.append("--") 

time.sleep(1)
# Making the dataframe 
df=pd.DataFrame({'Book Name': book_name,
                    'Author Name': author_name,
                    'Volume Sold': volume_sold,
                    'Publisher': publisher,
                    'Genre' : genre})
df

,Book Name,Author Name,Volume Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

9. Scrape the details most watched tv series of all time from imdb.com.

Url = https://www.imdb.com/list/ls095964455/

You have to find the following details:

A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

In [51]:
#send get request to the webpage server to get the source code of the page
url = "https://www.imdb.com/list/ls095964455/"
page = requests.get(url)

#to see page content
soup = BeautifulSoup(page.content)

#pathe for chromedriver
driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

#empty lists to store the data
name = []
year_span = []
genre = []
runtime = []
ratings = []
votes = []


# Scraping the series name
try:
    for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
        name.append(i.text)
except NoSuchElementException:
    name.append("--")
    
time.sleep(1)
# Scraping year span    
try:
    for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]"):
        year_span.append(i.text)
except NoSuchElementException:
    year_span.append("--")
    
time.sleep(1)
# Scraping Genre    
try:
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p/span[5]"):
        genre.append(i.text)
except NoSuchElementException:
    genre.append("-")

time.sleep(1)
#Scraping Runtime
try:
    for i in driver.find_elements_by_xpath("//span[@class='runtime']"):
        runtime.append(i.text)
except NoSuchElementException:
    runtime.append("-") 

time.sleep(1)
#Scraping movie ratings
try:
    for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]"):
        ratings.append(i.text)
except NoSuchElementException:
    ratings.append("-")

time.sleep(1)
# Scraping no.of votes
try:
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p[4]/span[2]"):
        votes.append(i.text)
except NoSuchElementException:
    votes.append("-")

time.sleep(1)
# making a dataframe 
df=pd.DataFrame({'Name':name,
                 'Year Span':year_span,
                 'Genre':genre,
                 'Run-Time':runtime,
                 'Ratin':ratings,
                 'Votes':votes})
df

,Name,Year Span,Genre,Run-Time,Ratin,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,882,220"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"915,624"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"904,072"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"270,874"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"231,269"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"45,885"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"56,757"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"177,264"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"36,872"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"203,480"

10. Details of Datasets from UCI machine learning repositories.

Url = https://archive.ics.uci.edu/

You have to find the following details:

A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the Show All Dataset page through code.

In [64]:
#path for chromedriver
driver = webdriver.Chrome(executable_path='chromedriver.exe')

# to open the webpage
url = 'https://archive.ics.uci.edu/'
driver.get(url)
driver.maximize_window()

time.sleep(2)

#clicking on view all datasets option
view=driver.find_element_by_xpath("//a[@href='datasets.php']")
view.click()

time.sleep(1)

In [66]:
#empty lists to store the data    
name=[]
type=[]
task=[]
attribute=[]
no_of_instance=[]
no_of_attribute=[]
year=[]

# Scraping name of the dataset
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        name.append(i.text)
except NoSuchElementException:
    name.append('--')

time.sleep(1)
# Scraping datatype
try:
    typ=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in typ[1:]:
        type.append(i.text)
except NoSuchElementException:
    type.append('--')
    
time.sleep(1)
# Scraping default task
try:
    tsk=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in tsk[1:]:
        task.append(i.text)
except NoSuchElementException:
    task.append('--')

time.sleep(1)
# Scraping type of attribute
try:
    attri=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in attri[1:]:
        attribute.append(i.text)
except NoSuchElementException:
    attribute.append('--')

time.sleep(1)
#Scraping no. of instances
try:
    inst=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in inst[1:]:
        no_of_instance.append(i.text)
except NoSuchElementException:
    no_of_instance.append('--')
    
time.sleep(1)       
# Scraping no. of attributes
try:
    num=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in num[1:]:
        no_of_attribute.append(i.text)
except NoSuchElementException:
    no_of_attribute.append('--')
        
# Scrapping the year details
try:
    yr=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in yr[1:]:
        year.append(i.text)
except NoSuchElementException:
    year.append('--')
    
# Creating the dataframe
df=pd.DataFrame({"Dataset Name":name,
                 "Data Type":type,
                 "Default Task":task,
                 "Attribute Type":attribute, 
                 "No of Instances":no_of_instance,
                 "No of Attributes":no_of_attribute,
                 "Year":year})
df

,Dataset Name,Data Type,Default Task,Attribute Type,No of Instances,No of Attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021